Add support for logs data
Altinity/clickhouse-grafana pull request #332
Opened 2021-03-31 22:17 UTC by pixelsquared

fixes #331 

This is my attempt at adding support for logs to clickhouse-grafana.

I have not added any tests yet.

2021-04-01 13:16 UTC, pixelsquared commented
@Slach Could you review this and tell me what you think?

2021-04-01 15:58 UTC, Slach requested changes
thanks a lot for your efforts, did you try to run `docker-compose run --rm frontend_builder` in your branch?
currently, I see the following error:
```
ERROR in module.js from UglifyJs
Unexpected token: keyword «const» [../node_modules/apache-arrow/type.js:19,0][module.js:4960,0]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
```

2021-04-01 18:06 UTC, pixelsquared commented
> thanks a lot for your efforts, did you try to run `docker-compose run --rm frontend_builder` in your branch?
> currently, I see the following error:
> 
> ```
> ERROR in module.js from UglifyJs
> Unexpected token: keyword «const» [../node_modules/apache-arrow/type.js:19,0][module.js:4960,0]
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> ```

I am not getting that error when I run the frontend_builder. What command did you run to get that error?

2021-04-01 18:48 UTC, pixelsquared commented on src/sql_series.ts
> +            case 'DateTime64':
Added the additional types.

2021-04-02 06:35 UTC, Slach commented
> I am not getting that error when I run the frontend_builder. What command did you run to get that error?
Sorry, I know nothing, how you tested your changes
just simple steps to reproduce
```
git clone https://github.com/pixelsquared/clickhouse-grafana.git ./clickhouse-grafana-logs
cd ./clickhouse-grafana-logs
docker-compose run --rm frontend_builder
```
but I tied it from scratch now, and it doesn't reproduce anymore
nice ;)
after 
```
docker-compose run --rm plugin_signer
docker-compose up -d clickhouse grafana
```

I open `http://localhost:3000` and see plugin loaded
but when I try to create a new dashboard
I got the following error
![image](https://user-images.githubusercontent.com/105560/113387433-c17cca80-93a5-11eb-9a32-d09aba6f48f5.png)
Also when I try to test datasources
I got same error
![image](https://user-images.githubusercontent.com/105560/113388234-461c1880-93a7-11eb-95b9-373891a111c1.png)
and in Console i see following stacktrace
![image](https://user-images.githubusercontent.com/105560/113388283-6055f680-93a7-11eb-8d4d-229646f559d7.png)

I tried `GRAFANA_VERSION=7.4.3 docker-compose up -d grafana` and `GRAFANA_VERSION=7.5.2 docker-compose up -d grafana`, same result

2021-04-02 06:45 UTC, Slach requested changes
could you please provide a functinal tests and documentation with screenshots?

2021-04-02 17:41 UTC, pixelsquared commented
Sorry some stuff came up and I will not have time to work on this until next week. I will add tests I just wanted to make sure I was going in the right direction first. I am not sure what is causing those error you are seeing I will work on it next week.

2021-04-09 08:39 UTC, Slach commented
@pixelsquared any news and progress on this PR?

2021-04-09 19:27 UTC, pixelsquared commented
Sorry about the lack of response I got busy with some stuff but I am back to working on this now.

2021-04-13 21:31 UTC, pixelsquared commented
For screenshots in the documentation where should I put the images?

2021-04-14 02:36 UTC, Slach commented
we use GitHub user content
just copy the image to buffer
and paste it via CTRL+V (cmd+V) inside text area for comments in this PR
you will get text link something like 
```
![image](https://user-images.githubusercontent.com/105560/114646031-f10bcb00-9cf3-11eb-8832-3f0844c4acc6.png)
```
if you copy and paste it to README.md you will get something like
after markdown formatting

![image](https://user-images.githubusercontent.com/105560/114646031-f10bcb00-9cf3-11eb-8832-3f0844c4acc6.png)

2021-04-23 10:18 UTC, Slach commented
@pixelsquared any progress?
don't give up ;) feel free to ask anything, I try to help you

2021-06-10 08:06 UTC, medvetskiy commented
Hi guys,
do you have any progress?
it is very useful feature for making cool dashboards.

2021-06-10 08:08 UTC, Slach commented
no progress more than 2 month
@pixelsquared will you continue efforts?

2022-05-26 06:06 UTC, closed without merging