Issue 495: Add default values for query builder inside connection settings
Altinity/clickhouse-grafana pull request #567
Opened 2024-05-27 19:13 UTC by lunaticusgreen

fix #495

2024-05-31 13:26 UTC, antip00 commented
Issues:

- [ ] Can't create new datasource, `save and test` button returns nothing
![Screenshot from 2024-05-31 16-20-53](https://github.com/Altinity/clickhouse-grafana/assets/44409195/01981427-5414-401c-a5cd-c25789776616)
![Screenshot from 2024-05-31 16-21-09](https://github.com/Altinity/clickhouse-grafana/assets/44409195/5149a13c-7648-447b-add6-e3903e8b52cf)



- [ ] I think we need to move `default database` to other section
![Screenshot from 2024-05-31 16-21-09](https://github.com/Altinity/clickhouse-grafana/assets/44409195/d61b77af-1817-421a-b80a-edde814431b3)

2024-06-14 07:04 UTC, Slach requested changes

2024-06-14 07:04 UTC, Slach commented on src/views/ConfigEditor/FormParts/DefaultValues/DefaultValues.tsx
> +      {/*<h6>Connection Parameters</h6>*/}
remove unused code

2024-06-14 07:04 UTC, Slach commented on src/views/QueryEditor/QueryEditor.tsx
> +    // !!!!!!!!
what means this comment?

2024-06-14 07:04 UTC, Slach commented on src/views/QueryEditor/components/QueryTextEditor/editor/initiateEditor.ts
> +Method, Variable, Constant, Keyword, TypeParameter, Text
why new line without ident?

2024-06-14 07:26 UTC, Slach commented
could run `git pull origin master`?

2024-06-18 15:36 UTC, Slach commented
@lunaticusgreen 
![image](https://github.com/Altinity/clickhouse-grafana/assets/105560/0a26bd6d-5178-4319-93c8-5308d2b53e29)

https://github.com/Altinity/clickhouse-grafana/actions/runs/9567400079/job/26375045064?pr=567
test failed 
"Save and Test" button return nothing, expect error, look to screenshot

2024-06-18 16:47 UTC, Slach approved these changes

2024-06-18 16:47 UTC, merged