Add customizable adhoc SQL query for select adhoc values
Altinity/clickhouse-grafana pull request #655
Opened 2024-11-02 08:43 UTC by lunaticusgreen

fix #330 , can be merged after https://github.com/Altinity/clickhouse-grafana/pull/654

2024-11-06 14:16 UTC, alon-cheq commented
Hi [654](https://github.com/Altinity/clickhouse-grafana/pull/654) was merged, any update on this fix?

2024-11-11 07:53 UTC, Slach commented
When open or create new Datasource i expected SQL query in adhoc field
![image](https://github.com/user-attachments/assets/6899a15a-a406-4a7a-8c3e-9904eb686e79)

2024-11-11 08:23 UTC, Slach commented
![image](https://github.com/user-attachments/assets/05286b80-a7d4-4264-8865-2cfafa530db9)

2024-11-11 08:31 UTC, Slach commented
```
Details
Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    at QueryEditor (webpack-internal:///./views/QueryEditor/QueryEditor.tsx:81:13)
```

but `QueryEditor.tsx` contains only 78 lines, this is really weird

2024-11-11 13:25 UTC, Slach commented
@antip00 instead of create tests for already tested macros, better will create test which cover works with adhoc macros and cover new functionality

2024-11-13 15:00 UTC, Slach commented
@lunaticusgreen still get error 
open http://localhost:3000/d/Bnh59Trnk/24-adhoc-2b-24-variable3a-text-formatting?from=now-6h&to=now&var-adhoc_variable=&var-split=service_name&editPanel=2

and remove NL (press <X>)
and after reload adhoc stop works


![image](https://github.com/user-attachments/assets/97333401-61e9-4f94-afd3-04dd4996ab13)

2024-11-17 03:45 UTC, Slach approved these changes

2024-11-19 02:35 UTC, Slach requested changes

2024-11-19 02:35 UTC, Slach commented on src/datasource/datasource.ts
> +    const adhocFilters = getAdhocFilters(this.adHocFilter?.datasource?.name || 'clickhouse',this.uid )
Wrong fix
we don't have default data source name
remove `clickhouse` here

2024-11-20 04:46 UTC, Slach approved these changes

2024-11-20 06:59 UTC, Slach commented
@lunaticusgreen e2e test failed

just add new dashboard -> add new visualization (default clickhouse-direct datasource)

got following error
```
An unexpected error happened
Details
TypeError: Cannot read properties of undefined (reading 'uid')

    at QueryEditor (webpack-internal:///./views/QueryEditor/QueryEditor.tsx:82:13)
```

![image](https://github.com/user-attachments/assets/3190c477-39d6-4976-8031-0f9c07e9654b)

2024-11-22 12:48 UTC, antip00 commented
If you change adhoc variable in panel, it do not changes in reformatted query
[Screencast from 2024-11-22 15-46-12.webm](https://github.com/user-attachments/assets/9b2b910c-ce36-44dd-98a5-7a810700f342)

2024-11-22 14:13 UTC, Slach commented
@lunaticusgreen 
it tried `GF_FEATURE_TOGGLES_PUBLICDASHBOARDSSCENE: false` in environment
and it reproduced
`CLICKHOUSE_PLUGIN_VERSION=3.2.3 docker compose up -d grafana_external_install`

http://localhost:3001/d/Bnh59Trnk/24-adhoc-2b-24-variable3a-text-formatting?editPanel=2

all works fine changing in adhoc control changed in Generated SQL
![image](https://github.com/user-attachments/assets/a7f2bb46-9625-4ba3-ace2-2e80265accde)


looks like we broke it in 2.3.4
`CLICKHOUSE_PLUGIN_VERSION=3.2.4 docker compose up -d grafana_external_install`

the same URL
http://localhost:3001/d/Bnh59Trnk/24-adhoc-2b-24-variable3a-text-formatting?editPanel=2

![image](https://github.com/user-attachments/assets/a5b6a214-1858-48eb-b06b-450f04c9eb49)

issue-330 branch little bit different behavior

```
git checkout issue-330
git pull origin issue-330
npm run dev
npm run server
```

panel in 3000 port
http://localhost:3000/d/Bnh59Trnk/24-adhoc-2b-24-variable3a-text-formatting?editPanel=2

![image](https://github.com/user-attachments/assets/550901ab-209c-433c-8ec9-8dec15cc6d51)


`GRAFANA_VERSION=10.4.3 docker compose up -d grafana`
http://localhost:3000/d/Bnh59Trnk/24-adhoc-2b-24-variable3a-text-formatting?editPanel=2

![image](https://github.com/user-attachments/assets/2afc4304-2ea1-4eef-93ae-af0e6a70af2b)

this is definitely bug and shall be fixed

2024-11-22 19:48 UTC, merged