remove all duplicated logic, move all macroses and query parsing functionality to golang, and compile golang parser to WASM
Altinity/clickhouse-grafana pull request #690
Opened 2024-12-10 19:25 UTC by lunaticusgreen

fix https://github.com/Altinity/clickhouse-grafana/issues/688

2024-12-11 07:45 UTC, Slach commented on pkg/eval_query_test.go
> +			"/* comment */ SELECT t, datacenter, sum(tx_kbytesRate) AS tx_kbytesRateAgg, sum(rx_bytesRate) AS rx_bytesRateAgg"+
Looks like this is not `go fmt` output

2024-12-11 08:04 UTC, Slach commented on pkg/eval_query_test.go
> +			"/* comment */ SELECT t, datacenter, sum(tx_kbytesRate) AS tx_kbytesRateAgg, sum(rx_bytesRate) AS rx_bytesRateAgg"+
hm actually it is go fmt `output` ;)

2024-12-11 08:11 UTC, Slach commented on src/datasource/datasource.ts
> -          result = sqlSeries.toAnnotation(response.data, response.meta);
Where is serialization implemented now?

2024-12-11 16:03 UTC, Slach requested changes

2024-12-11 16:03 UTC, Slach commented on src/datasource/response_parser.ts
> +    console.log(columns)
remove it

2024-12-16 14:55 UTC, Slach commented
@antip00 could you look, why tests failed after startup?

2024-12-16 15:01 UTC, antip00 commented
> @antip00 could you look, why tests failed after startup?

same as there https://github.com/Altinity/clickhouse-grafana/actions/runs/12239054692/job/34140041216, some problems with golang, just need to restart it I guess

2024-12-17 07:53 UTC, Slach requested changes

2024-12-17 07:53 UTC, Slach commented on pkg/datasource.go
> +	mux.HandleFunc("/replace-time-filters", func(w http.ResponseWriter, r *http.Request) {
you can use function directly without wrappers
just `mux.HandleFunc("/replace-time-filters", replaceTimeFilters)`

2025-01-09 16:43 UTC, Slach commented
![image](https://github.com/user-attachments/assets/aa0658a6-3e4a-4072-be47-5f09846ca5f7)

```yaml
git checkout v4
git pull origin v4
docker compose up -d grafana
```

why $from and $to didn't replace?

2025-02-07 04:52 UTC, Slach requested changes

2025-02-07 04:52 UTC, Slach commented on src/datasource/wasm.ts
> +    const compressedBuffer = await fetch('/public/plugins/vertamedia-clickhouse-datasource/static/backend.wasm.gz').then(resp =>
Static hardcoded path here, bad idea,
we need to look into `grafana` and figure out how Grafana itself fetches artifacts, to allow use cases when Grafana installed into `http://host/subpath/`

2025-03-03 12:19 UTC, Slach requested changes

2025-03-03 12:19 UTC, Slach commented on tests/testflows/regression.py
> +    "/Grafana Datasource Plugin For Clickhouse/e2e/many categories/*": [
but we resolved issue?, we need to comment it

2025-03-03 12:19 UTC, Slach commented on tests/testflows/tests/automated/e2e.py
> -def many_categories(self):
wrong way, why we remove tests?

2025-03-03 12:19 UTC, Slach commented on tests/testflows/tests/automated/functions.py
> +            assert expected_reformatted_query.replace("\n", "") in sql_editor.get_reformatted_query(query_name='A'), error()
maybe space instead of empty line?

2025-03-06 16:12 UTC, Slach requested changes

2025-03-06 16:12 UTC, Slach commented on tests/testflows/regression.py
> +    "/Grafana Datasource Plugin For Clickhouse/e2e/many categories/*": [
please add comment back here

2025-03-10 05:02 UTC, merged